[package]
name = "cln"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
home = "0.5"
rayon = "1.10"
tempfile = "3.10"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
assert_cmd = "2.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"

