[package]
name = "cln-bin"
edition = "2021"
version = "0.1.0"

[[bin]]
name = "cln"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
cln = { path = "../cln" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.38.0", default-features = false, features = ["macros"]}

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"

